spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking-route
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1
        - id: feedback-route
          uri: lb://feedback-service
          predicates:
            - Path=/feedback/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
